### ISSUE TITLE
Error on using pretrained Yolov4-320

### ISSUE THREAD

**Issue by bibekyess** [robotics-upo/og-sgg#1]
Thank you for your great work and contribution. :+1:  I am facing some problems while running your code.
I saw that you have used "Yolo-v4-320" as the pretrained model, but I also tried to download the pretrained weights in the form of ".pb" files and I get the following error:
`    
While executing: features,yolodata = mdl_yolo(img),     
ValueError: not enough values to unpack (expected 2, got 1)
`
So, can you please upload the pretrained yolo model you used? or help me solve this problem?
Thank you for your time and help.

**Comment by feramozur** [comment]
Hello,
Thank you for your interest in OG-SGG. I have just uploaded the pretrained YOLOv4 model I used in this project: [link](https://robotics.upo.es/~famozur/ogsgg/yolov4-320.tar.xz). I'm hoping that helps.

**Comment by bibekyess** [comment]
OK, Thank you!!
